name: PR Build

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.17.0

      - name: Install dashboard dependencies
        working-directory: ./app/dashboard
        run: npm ci

      - name: Build dashboard
        working-directory: ./app/dashboard
        run: VITE_BASE_API=/api/ npm run build --if-present -- --outDir build --assetsDir statics

      - name: Create 404.html
        working-directory: ./app/dashboard
        run: cp ./build/index.html ./build/404.html

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: xmohammad1/marzban:pr-${{ github.event.pull_request.number }}

